from django.conf.urls import patterns, url
from django.conf.urls.defaults import *

urlpatterns = patterns('markets.views',
	url(r'^$', 'home', name='home'),
	url(r'^signup/$', 'signup', name='signup'),
	url(r'^signin/$', 'signin', name='signin'),
	url(r'^signout/$', 'signout', name='signout'),
	url(r'^trader/(?P<idUser>\d+)/activate$', 'toggleActivateTrader', name='toggleActivateTrader'),
	url(r'^trader/(?P<idUser>\d+)/$', 'showTrader', name='showTrader'),
	url(r'^traders/$', 'allTraders', name='allTraders'),
	url(r'^cancelorder/(?P<idLimit>\d+)/$', 'cancelOrder', name='cancelOrder'),
	url(r'^cancelall/(?P<idMarket>\d+)/(?P<idUser>\d+)/(?P<side>\d+)/$', 'cancelAll', name='cancelAll'),
	url(r'^deletemarket/(?P<idMarket>\d+)/$', 'deleteMarket', name='deleteMarket'),
	url(r'^settleevent/(?P<idEvent>\d+)/(?P<idMarket>\d+)/$', 'settleEvent', name='settleEvent'),
	url(r'^unsettleevent/(?P<idEvent>\d+)/$', 'unsettleEvent', name='unsettleEvent'),
	url(r'^deleteevent/(?P<idEvent>\d+)/$', 'deleteEvent', name='deleteEvent'),
	url(r'^deleteglobalevent/(?P<idgEvent>\d+)/$', 'deleteGlobalEvent', name='deleteGlobalEvent'),
	url(r'^market/(?P<idMarket>\d+)/$', 'showMarket', name='showMarket'),
	url(r'^market/(?P<idMarket>\d+)/a/$', 'showMarketb', name='showMarketb'),
	url(r'^refreshmarket/(?P<idMarket>\d+)/$', 'refreshMarket', name='refreshMarket'),
	url(r'^event/(?P<idEvent>\d+)/$', 'showEvent', name='showEvent'),
	url(r'^event/(?P<idEvent>\d+)/(?P<page>\d+)/$', 'showEvent', name='eventList'),
	url(r'^globalevent/(?P<idgEvent>\d+)/$', 'showGlobalEvent', name='globalEvent'),
	url(r'^globalevent/(?P<idgEvent>\d+)/(?P<page>\d+)/$', 'showGlobalEvent', name='globalEventList'),
	url(r'^globalevents/$', 'allGlobalEvents', name='allGlobalEvents'),
	url(r'^globalevents/(?P<page>\d+)$', 'allGlobalEvents', name='allGlobalEventsList'),
	url(r'^createglobalevent/$', 'createGlobalEvent', name='createGlobalEvent'),
	url(r'^createevent/(?P<idgEvent>\d+)/$', 'createEvent', name='createEvent'),
	url(r'^createmarket/(?P<idEvent>\d+)/$', 'createMarket', name='createMarket'),
	url(r'^createcodes/$', 'createCodes'),
	url(r'^contact/$', 'contact', name='contact'),
	url(r'^help/$', 'help'),
	url(r'^about/$', 'about'),
)